### ISSUE TITLE
Linebreak-style error when exec docker-compose up

### ISSUE THREAD

**Issue by anicarrr** [pomber/fame#9]
An error about linebreak-styling araise when you run docker-compose up. 

It shows "Expected linebreaks to be 'LF' but found 'CRLF'".

We should override the ESLint options to ignore this.

**Comment by pomber** [comment]
Isn't this the same as #6?

**Comment by anicarrr** [comment]
My bad! I haven't updated my repo and I totally forgot I already done this! Just close it!
